
- name: update /etc/hosts
  shell: /etc/cron.daily/scanip

- name: mount share fileserver in /mnt/share
  mount:
    path: /mnt/share
    src: "fileserver:/share"
    fstype: nfs
    opts: "user,defaults,_netdev,timeo=14,soft"
    state: mounted
