---
- import_playbook: minimal.yml

- hosts: local
  become: yes

  tasks:
        
    - include_role:
        name: programming
        
    - include_role:
        name: writing
    
    - include_role:
        name: disks
    
    - include_role:
        name: backup

