---
- hosts: local
  become: yes

  tasks:
    - include_role:
        name: workstation
      vars:
        anaconda_version: 2019.03
    
    # this assumes that an account 'jacquem' has been created
    - include_role:
        name: user
      vars:
        user_login: jacquem
        user_name: "Vincent Jacquemet"
        user_email: "vincent.jacquemet@umontreal.ca"
    
    # this assumes disks have been renamed to "data1", "data2", etc.
    - include_role:
        name: disks
    
    - include_role:
        name: backup
    
    # this updates IP addresses based on a list of MAC addresses
    - include_role:
        name: scanip
    
    # requires scanip
    - include_role:
        name: share
