# modify file /etc/gitconfig
- name: set system-wide git config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - {name: core.editor, value: nano}
    - {name: color.ui, value: "true"}
