# requirements for ansible module dconf
- name: install python3-devel
  dnf:
    name: python3-devel
    state: present

- name: install gnome-extensions-app
  dnf:
    name: gnome-extensions-app
    state: present

- name: install psutil python packages
  pip:
    name:
      - psutil
    executable: /usr/bin/pip3

