
- name: create download directory
  file: 
    path: "{{ anaconda_download_dest }}"
    state: directory

- name: find latest anaconda version
  shell:
    cmd: "wget -q -O - repo.anaconda.com/archive | grep Anaconda3-20.*Linux-x86_64 | sort | tail -1 | cut -d- -f2,3"
  register: getanaconda

- name: anaconda version
  debug:
    msg: "{{ getanaconda.stdout }}"

- name: download anaconda
  get_url:
    url: "{{ anaconda_url }}"
    dest: "{{ anaconda_path }}"
  register: anaconda_download_anaconda
  until: anaconda_download_anaconda is succeeded
  retries: 3

- name: install anaconda
  command: bash {{ anaconda_path }} -b -p {{ anaconda_prefix }}
  args:
    creates: "{{ anaconda_prefix }}"

- name: fix libstdc++ version in anaconda
  ansible.builtin.shell: |
    rm /opt/anaconda/lib/libstdc++.so
    rm /opt/anaconda/lib/libstdc++.so.6
    ln -s /usr/lib64/libstdc++.so.6 /opt/anaconda/lib/libstdc++.so.6
    ln -s /opt/anaconda/lib/libstdc++.so.6 /opt/anaconda/lib/libstdc++.so

# with this change, 'sudo pip' refers to anaconda pip and not /usr/bin/pip
- name: update sudo secure_path
  lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults.*secure_path ='
    line: "Defaults    secure_path = {{ anaconda_prefix }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    validate: 'visudo -cf %s'


