- name: create download directory
  file: 
    path: "{{ anaconda_download_dest }}"
    state: directory

- name: download anaconda
  get_url:
    url: "{{ anaconda_url }}"
    dest: "{{ anaconda_path }}"
  register: anaconda_download_anaconda
  until: anaconda_download_anaconda is succeeded
  retries: 3

- name: install anaconda
  command: bash {{ anaconda_path }} -b -p {{ anaconda_prefix }}
  args:
    creates: "{{ anaconda_prefix }}"


# with this change, 'sudo pip' refers to anaconda pip and not /usr/bin/pip
- name: update sudo secure_path
  lineinfile:
    path: /etc/sudoers
    regexp: '^Defaults.*secure_path ='
    line: "Defaults    secure_path = {{ anaconda_prefix }}/bin:usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    validate: 'visudo -cf %s'


