- name: install programming tools and libraries
  dnf:
    name:
      - make
      - gcc-c++
      - SFCGAL
      - CGAL-devel
      - eigen3-devel
      - OpenMesh
      - OpenMesh-devel
      - autotrace
      - lapack
      - octave
      - freeglut
      - freeglut-devel
      - ImageMagick
      - mesa-libOSMesa
      - mesa-libOSMesa-devel
    state: latest

- name: uninstall ffmpeg-free
  dnf:
    name:
      - ffmpeg-free
      - ffmpeg-free--devel
    state: absent

- name: install ffmpeg
  dnf:
    name:
      - ffmpeg
      - ffmpeg-devel
    state: latest
    allowerasing: true
