- name: install programming tools and libraries
  dnf:
    name:
      - make
      - gcc-c++
      - SFCGAL
      - CGAL-devel
      - eigen3-devel
      - OpenMesh
      - OpenMesh-devel
      - autotrace
      - lapack
      - octave
      - freeglut
      - freeglut-devel
      - ffmpeg
      - ffmpeg-devel
      - ImageMagick
    state: latest
    allowerasing: true # to replace ffmpeg-free with the rpmfusion package
