# default configuration for all users

- name: bash aliases and environment variables
  blockinfile:
    path: /etc/profile.d/custom.sh
    create: yes
    block: |
      alias l='ls'
      alias ll='ls -lh'
      alias cdl='cd .. ; ls'
      export EDITOR=/usr/bin/nano
      export PYTHONPATH=$PYTHONPATH:$HOME/python
      export PATH=$HOME/bin:/opt/anaconda/bin:$PATH

- name: bash fancy color prompt
  blockinfile:
    path: /etc/profile.d/color_prompt.sh
    create: yes
    block: |
      # Colors in terminal (bash)
      if [[ ! -z $BASH ]]; then
          if [[ $EUID -eq 0 ]]; then
              PS1="\[\033[33m\][\[\033[m\]\[\033[31m\]\u@\h\[\033[m\] \[\033[33m\]\W\[\033[m\]\[\033[33m\]]\[\033[m\] # "
          else
              PS1="\[\033[36m\][\[\033[m\]\[\033[34m\]\u@\h\[\033[m\] \[\033[32m\]\W\[\033[m\]\[\033[36m\]]\[\033[m\] $ "
          fi
      fi


