# update all packages
- name: update fedora
  dnf:
    name: "*"
    state: latest

- name: install basic packages
  dnf:
    name:
      - nano
      - cronie
      - cronie-anacron
    state: latest

- name: install automatic update
  dnf:
    name:
      - dnf5-plugin-automatic
    allowerasing: true
    state: present

- name: dnf-automatic configuration file
  template:
    src: automatic.conf.j2
    dest: /etc/dnf/dnf5-plugins/automatic.conf

- name: Start and enable systemd timer for dnf-automatic
  service:
    name: dnf5-automatic.timer
    state: started
    enabled: yes

- name: enable crond
  systemd:
    name: crond.service
    state: started
    enabled: yes

- name: ensure GPG check enabled for local packages
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: localpkg_gpgcheck
    value: '1'
    create: true

