# update all packages
- name: update fedora
  dnf:
    name: "*"
    state: latest
    
- name: install basic packages
  dnf:
    name:
      - dnf-automatic
      - nano
      - cronie
      - cronie-anacron
    state: latest

- name: dnf-automatic configuration file
  template:
    src: automatic.conf.j2
    dest: /etc/dnf/automatic.conf

- name: Start and enable systemd timer for dnf-automatic
  service:
    name: dnf-automatic-install.timer
    state: started
    enabled: yes

- name: enable crond
  systemd: 
    name: crond.service
    state: started
    enabled: yes

- name: ensure GPG check enabled for local packages
  ini_file:
    dest: /etc/dnf/dnf.conf
    section: main
    option: localpkg_gpgcheck
    value: '1'
    create: true

