

- name: install rpmfusion-free dnf repo
  dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_version }}.noarch.rpm 
    state: latest
    disable_gpg_check: yes


- name: install rpmfusion-nonfree dnf repo
  dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_version }}.noarch.rpm
    state: latest
    disable_gpg_check: yes
